[tool.poetry]
name = "deepuq"
version = "0.1.0"
description = ""
authors = ["beckynevin <beckynevin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpyro = "^0.13.2"
jupyter = "^1.0.0"
numpy = "^1.26.0"
scikit-learn = "^1.3.1"
seaborn = "^0.12.2"
torch = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
